## import dữ liệu

In [20]:
import pandas as pd
import numpy as np

## Load dữ liệu

Ta sử dụng file đã merged để làm việc.

In [21]:
df=pd.read_csv("../../Dataset/data_cleaned/country_vaccinations_merged.csv",  index_col=0)
df.head(10)

,iso_code,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccine_id,vaccine_names,source_id,source_name,source_website
0,AFG,Afghanistan,2/22/2021,0,0,0,0,0,0.00,0.00,0.0,0,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
1,AFG,Afghanistan,2/23/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
2,AFG,Afghanistan,2/24/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
3,AFG,Afghanistan,2/25/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
4,AFG,Afghanistan,2/26/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
5,AFG,Afghanistan,2/27/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
6,AFG,Afghanistan,2/28/2021,8200,8200,0,0,1367,0.02,0.02,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
7,AFG,Afghanistan,3/1/2021,0,0,0,0,1580,0.00,0.00,0.0,41,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
8,AFG,Afghanistan,3/10/2021,0,0,0,0,2862,0.00,0.00,0.0,74,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/
9,AFG,Afghanistan,3/11/2021,0,0,0,0,2862,0.00,0.00,0.0,74,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/

## Tạo các trường tính toán mới

### 1. Drop-out rate
(people_vaccinated-people_fully_vaccinated) / people_vaccinated *100

In [22]:
df["dropout_date"]=np.where(
    df["people_vaccinated"]>0,
    ((df["people_vaccinated"]-df["people_fully_vaccinated"])/df["people_vaccinated"])*100,0
)
df.head(10)

,iso_code,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccine_id,vaccine_names,source_id,source_name,source_website,dropout_date
0,AFG,Afghanistan,2/22/2021,0,0,0,0,0,0.00,0.00,0.0,0,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0
1,AFG,Afghanistan,2/23/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0
2,AFG,Afghanistan,2/24/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0
3,AFG,Afghanistan,2/25/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0
4,AFG,Afghanistan,2/26/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0
5,AFG,Afghanistan,2/27/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0
6,AFG,Afghanistan,2/28/2021,8200,8200,0,0,1367,0.02,0.02,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,100.0
7,AFG,Afghanistan,3/1/2021,0,0,0,0,1580,0.00,0.00,0.0,41,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0
8,AFG,Afghanistan,3/10/2021,0,0,0,0,2862,0.00,0.00,0.0,74,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0
9,AFG,Afghanistan,3/11/2021,0,0,0,0,2862,0.00,0.00,0.0,74,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0

### 2. Số lượng loại vaccine đang được sử dụng

In [23]:
df["vaccine_count"] = df["vaccine_id"].apply(
    lambda x: len([v for v in str(x).split(",") if v.strip()])
)
df.head(10)

,iso_code,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccine_id,vaccine_names,source_id,source_name,source_website,dropout_date,vaccine_count
0,AFG,Afghanistan,2/22/2021,0,0,0,0,0,0.00,0.00,0.0,0,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3
1,AFG,Afghanistan,2/23/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3
2,AFG,Afghanistan,2/24/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3
3,AFG,Afghanistan,2/25/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3
4,AFG,Afghanistan,2/26/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3
5,AFG,Afghanistan,2/27/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3
6,AFG,Afghanistan,2/28/2021,8200,8200,0,0,1367,0.02,0.02,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,100.0,3
7,AFG,Afghanistan,3/1/2021,0,0,0,0,1580,0.00,0.00,0.0,41,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3
8,AFG,Afghanistan,3/10/2021,0,0,0,0,2862,0.00,0.00,0.0,74,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3
9,AFG,Afghanistan,3/11/2021,0,0,0,0,2862,0.00,0.00,0.0,74,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3

### 3. Phân nhóm tỉ lệ bao phủ vaccine
Thấp      : < 30%

Trung bình: 30% - 70%

Cao       : > 70%

In [24]:
df["coverage_group"]=pd.cut(
    df["people_fully_vaccinated_per_hundred"],
    bins=[0, 30, 70, 100],
    labels=["Low", "Average", "High"],
    right=True,
    include_lowest=True
)
df.head(10)

,iso_code,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccine_id,vaccine_names,source_id,source_name,source_website,dropout_date,vaccine_count,coverage_group
0,AFG,Afghanistan,2/22/2021,0,0,0,0,0,0.00,0.00,0.0,0,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low
1,AFG,Afghanistan,2/23/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low
2,AFG,Afghanistan,2/24/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low
3,AFG,Afghanistan,2/25/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low
4,AFG,Afghanistan,2/26/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low
5,AFG,Afghanistan,2/27/2021,0,0,0,0,1367,0.00,0.00,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low
6,AFG,Afghanistan,2/28/2021,8200,8200,0,0,1367,0.02,0.02,0.0,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,100.0,3,Low
7,AFG,Afghanistan,3/1/2021,0,0,0,0,1580,0.00,0.00,0.0,41,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low
8,AFG,Afghanistan,3/10/2021,0,0,0,0,2862,0.00,0.00,0.0,74,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low
9,AFG,Afghanistan,3/11/2021,0,0,0,0,2862,0.00,0.00,0.0,74,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low

### 4. Tốc độ tiêm chủng trung bình 7 ngày

In [25]:
df["daily_vaccination_7d_avg"]=(
    df.groupby("country")["daily_vaccinations"]
      .transform(
          lambda x: x.rolling(
              window=7,
              min_periods=1
          ).mean()
      )
)
df.head(5)

,iso_code,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,...,daily_vaccinations_per_million,vaccine_id,vaccine_names,source_id,source_name,source_website,dropout_date,vaccine_count,coverage_group,daily_vaccination_7d_avg
0,AFG,Afghanistan,2/22/2021,0,0,0,0,0,0.0,0.0,...,0,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,0.000000
1,AFG,Afghanistan,2/23/2021,0,0,0,0,1367,0.0,0.0,...,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,683.500000
2,AFG,Afghanistan,2/24/2021,0,0,0,0,1367,0.0,0.0,...,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,911.333333
3,AFG,Afghanistan,2/25/2021,0,0,0,0,1367,0.0,0.0,...,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,1025.250000
4,AFG,Afghanistan,2/26/2021,0,0,0,0,1367,0.0,0.0,...,35,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,1093.600000

### 5. Chỉ số đà tiêm chủng
So sánh số liều tiêm trong ngày với tổng số liều đã tiêm

In [26]:
df["vaccination_momentum"] = df["daily_vaccinations"] / df["total_vaccinations"] * 100
df["vaccination_momentum"] = df["vaccination_momentum"].replace([np.inf, -np.inf], np.nan).fillna(0)
df.head(10)

,iso_code,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,...,vaccine_id,vaccine_names,source_id,source_name,source_website,dropout_date,vaccine_count,coverage_group,daily_vaccination_7d_avg,vaccination_momentum
0,AFG,Afghanistan,2/22/2021,0,0,0,0,0,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,0.000000,0.000000
1,AFG,Afghanistan,2/23/2021,0,0,0,0,1367,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,683.500000,0.000000
2,AFG,Afghanistan,2/24/2021,0,0,0,0,1367,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,911.333333,0.000000
3,AFG,Afghanistan,2/25/2021,0,0,0,0,1367,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,1025.250000,0.000000
4,AFG,Afghanistan,2/26/2021,0,0,0,0,1367,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,1093.600000,0.000000
5,AFG,Afghanistan,2/27/2021,0,0,0,0,1367,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,1139.166667,0.000000
6,AFG,Afghanistan,2/28/2021,8200,8200,0,0,1367,0.02,0.02,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,100.0,3,Low,1171.714286,16.670732
7,AFG,Afghanistan,3/1/2021,0,0,0,0,1580,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,1397.428571,0.000000
8,AFG,Afghanistan,3/10/2021,0,0,0,0,2862,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,1611.000000,0.000000
9,AFG,Afghanistan,3/11/2021,0,0,0,0,2862,0.00,0.00,...,"V002, V008, V009","BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech",S001,World Health Organization,https://covid19.who.int/,0.0,3,Low,1824.571429,0.000000

## Lưu file dữ liệu mới

In [27]:
df.to_csv("../../Dataset/data_cleaned/country_vaccinations_added_fields.csv")
print("\nĐã hoàn thành biến đổi dữ liệu!")

Đã hoàn thành biến đổi dữ liệu!