## Import thư viện

In [44]:
import pandas as pd

## Load dữ liệu

In [45]:
splitted = pd.read_csv("../../Dataset/data_cleaned/country_vaccinations_cleaned_splitted.csv")
country = pd.read_csv("../../Dataset/data_cleaned/country.csv")
vaccine = pd.read_csv("../../Dataset/data_cleaned/vaccine.csv")
country_iso_vaccine = pd.read_csv("../../Dataset/data_cleaned/country_iso_vaccine.csv")
source = pd.read_csv("../../Dataset/data_cleaned/source.csv")
by_manufacturer = pd.read_csv("../../Dataset/data_cleaned/country_vaccinations_by_manufacturer_cleaned.csv")

## Join bảng splitted với country

In [46]:
merged = splitted.merge(country, on="iso_code", how="left")
print(f"Sau khi join với country: {merged.shape}")
merged.head(3)

Sau khi join với country: (25862, 13)

,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,source_id,country
0,AFG,2/22/2021,0,0,0,0,0,0.0,0.0,0.0,0,S001,Afghanistan
1,AFG,2/23/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan
2,AFG,2/24/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan

## Join bảng source

In [47]:
merged = merged.merge(source, on="source_id", how="left")
print(f"Sau khi join với source: {merged.shape}")
merged.head(3)

Sau khi join với source: (25862, 15)

,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,source_id,country,source_name,source_website
0,AFG,2/22/2021,0,0,0,0,0,0.0,0.0,0.0,0,S001,Afghanistan,World Health Organization,https://covid19.who.int/
1,AFG,2/23/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan,World Health Organization,https://covid19.who.int/
2,AFG,2/24/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan,World Health Organization,https://covid19.who.int/

In [48]:
civ = (
    country_iso_vaccine
    .groupby("iso_code")["vaccine_id"]
    .apply(lambda x: ", ".join(x.drop_duplicates()))
    .reset_index()
)

merged = merged.drop(columns=["vaccine_id"], errors="ignore")

merged = merged.merge(
    civ,
    on="iso_code",
    how="left"
)

print(f"Sau khi join với country_iso_vaccine: {merged.shape}")

merged.head(3)

Sau khi join với country_iso_vaccine: (25862, 16)

,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,source_id,country,source_name,source_website,vaccine_id
0,AFG,2/22/2021,0,0,0,0,0,0.0,0.0,0.0,0,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"
1,AFG,2/23/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"
2,AFG,2/24/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"

## Join bảng country_iso_vaccine

In [49]:
civ = country_iso_vaccine[["iso_code", "vaccine_id"]].drop_duplicates()
merged.merge(civ, on="iso_code", how="left")
print(f"Sau khi join với country_iso_vaccine: {merged.shape}")
merged.head(3)

Sau khi join với country_iso_vaccine: (25862, 16)

,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,source_id,country,source_name,source_website,vaccine_id
0,AFG,2/22/2021,0,0,0,0,0,0.0,0.0,0.0,0,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"
1,AFG,2/23/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"
2,AFG,2/24/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"

## Join bảng vaccine

In [50]:
merged.merge(vaccine, on="vaccine_id", how="left")
print(f"Sau khi join với vaccine: {merged.shape}")
merged.head(3)

Sau khi join với vaccine: (25862, 16)

,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,source_id,country,source_name,source_website,vaccine_id
0,AFG,2/22/2021,0,0,0,0,0,0.0,0.0,0.0,0,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"
1,AFG,2/23/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"
2,AFG,2/24/2021,0,0,0,0,1367,0.0,0.0,0.0,35,S001,Afghanistan,World Health Organization,https://covid19.who.int/,"V002, V008, V009"

## Sắp xếp thứ tự cột

In [54]:
column_order = ['iso_code', 'country', 'date', 'total_vaccinations', 'people_vaccinated', 
                'people_fully_vaccinated', 'daily_vaccinations_raw', 'daily_vaccinations', 
                'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
                'daily_vaccinations_per_million', 'source_id', 'source_name', 
                'source_website', 'vaccine_id']
merged = merged[column_order]
merged = merged.sort_values(["country", "date"]).reset_index(drop=True)